/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import Business.EcoSystem;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.*;

import Business.Network.Network;
import Business.Organization.Organization;
import Business.Person.DonorsDirectory;
import Business.Person.Patients;
import Business.Person.PatientsDirectory;
import Business.Users.Users;
import Business.Waitlist.Wait;
import Business.WorkQueue.OrganProcureWorkRequest;
import Business.WorkQueue.WorkQueue;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import userinterface.DonorRole.DonorRegistrationJPanel;

/**
 *
 * @author namangupta
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private EcoSystem system;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private DonorsDirectory donorDirectory;

    public MainJFrame() {
        initComponents();
        system = dB4OUtil.retrieveSystem();
        this.setSize(1200, 800);
        
        if(system.getEmployeeId()==0){
            system.setEmployeeId(20211001);
        }
        if(system.getDonorId()==0){
            system.setDonorId(9001);
        }
        if(system.getPatientId()==0){
            system.setPatientId(1001);
        }
        if(system.getWaitList()==null){
            system.setWaitList(new ArrayList<>());
        }
        if(system.getWorkQueue()==null){
            system.setWorkQueue(new WorkQueue());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        logoutjPanel = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        logincontainer = new javax.swing.JPanel();
        loginjPanel = new javax.swing.JPanel();
        txtusername = new javax.swing.JTextField();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_donorRegisteration = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logoutjPanel.setBackground(new java.awt.Color(255, 255, 255));
        logoutjPanel.setMinimumSize(new java.awt.Dimension(100, 200));
        logoutjPanel.setPreferredSize(new java.awt.Dimension(250, 1080));
        logoutjPanel.setLayout(null);

        btn_logout.setBackground(new java.awt.Color(51, 51, 51));
        btn_logout.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        logoutjPanel.add(btn_logout);
        btn_logout.setBounds(0, 500, 100, 27);

        jSplitPane1.setLeftComponent(logoutjPanel);

        logincontainer.setBackground(new java.awt.Color(255, 255, 255));
        logincontainer.setPreferredSize(new java.awt.Dimension(1670, 1080));
        logincontainer.setLayout(new java.awt.CardLayout());

        loginjPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginjPanel.setMaximumSize(new java.awt.Dimension(1200, 800));
        loginjPanel.setPreferredSize(new java.awt.Dimension(1200, 800));
        loginjPanel.setLayout(null);

        txtusername.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        txtusername.setToolTipText("Enter your username");
        txtusername.setCaretColor(new java.awt.Color(204, 204, 204));
        txtusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtusernameKeyTyped(evt);
            }
        });
        loginjPanel.add(txtusername);
        txtusername.setBounds(390, 300, 360, 40);

        lblusername.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        lblusername.setText("Username:");
        loginjPanel.add(lblusername);
        lblusername.setBounds(300, 310, 90, 30);

        lblpassword.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        lblpassword.setText("Password:");
        loginjPanel.add(lblpassword);
        lblpassword.setBounds(300, 360, 90, 30);

        txtpassword.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        loginjPanel.add(txtpassword);
        txtpassword.setBounds(390, 350, 362, 40);

        btn_login.setBackground(new java.awt.Color(0, 0, 0));
        btn_login.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        loginjPanel.add(btn_login);
        btn_login.setBounds(470, 400, 114, 27);

        btn_donorRegisteration.setBackground(new java.awt.Color(255, 0, 51));
        btn_donorRegisteration.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        btn_donorRegisteration.setText("Want to become a Donor?");
        btn_donorRegisteration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_donorRegisterationRegisterationActionPerformed(evt);
            }
        });
        loginjPanel.add(btn_donorRegisteration);
        btn_donorRegisteration.setBounds(600, 620, 250, 27);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.gif"))); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        loginjPanel.add(jLabel1);
        jLabel1.setBounds(220, 110, 810, 580);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Organ Management System");
        loginjPanel.add(jLabel2);
        jLabel2.setBounds(270, 0, 690, 120);

        logincontainer.add(loginjPanel, "card2");

        jSplitPane1.setRightComponent(logincontainer);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        //btn_logout.setEnabled(false);
        //btn_donorRegisteration.setEnabled(true);
        //txtusername.setEnabled(true);
        //txtpassword.setEnabled(true);
        //btn_login.setEnabled(true);

        txtusername.setText("");
        txtpassword.setText("");

        logincontainer.removeAll();
        logincontainer.add("jpanel2",loginjPanel);
        CardLayout layout=(CardLayout)logincontainer.getLayout();
        layout.next(logincontainer);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void txtusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtusernameKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusernameKeyTyped

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // Get user name

        String userName = txtusername.getText();
        // Get Password
        char[] passwordCharArray = txtpassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        //Step1: Check in the system admin user account directory if you have the user
        Users userAccount=system.getUserAccountDirectory().authenticateUser(userName, password);

        Enterprise inEnterprise=null;
        Organization inOrganization=null;
        Network inNetwork=null;

        if(userAccount==null){
            //Step 2: Go inside each network and check each enterprise
            for(Network network:system.getNetworkList()){
                System.out.println(network.getEnterpriseList().getEnterpriseList());
                //Step 2.a: check against each enterprise
                for(Enterprise enterprise:network.getEnterpriseList().getEnterpriseList()){
                    System.out.println(enterprise);
                    userAccount=enterprise.getUserAccountDirectory().authenticateUser(userName, password);
                    inNetwork=network;
                    if(userAccount==null){
                        //Step 3:check against each organization for each enterprise
                        for(Organization organization:enterprise.getOrganizationDirectory().getListOfOrganizations()){
                            userAccount=organization.getUserAccountDirectory().authenticateUser(userName, password);
                            if(userAccount!=null){
                                inNetwork=network;
                                inEnterprise=enterprise;
                                inOrganization=organization;
                                break;
                            }
                        }
                    }
                    else{
                        inEnterprise=enterprise;
                        break;
                    }
                    if(inOrganization!=null){
                        break;
                    }
                }
                if(inEnterprise!=null){
                    break;
                }
            }
        }

        if(userAccount==null){
            JOptionPane.showMessageDialog(null, "Invalid credentials");
            return;
        }
        else{
            CardLayout layout=(CardLayout)logincontainer.getLayout();
            logincontainer.add("workArea",userAccount.getRole().createWorkArea(logincontainer, userAccount, inOrganization, inEnterprise, system, inNetwork, donorDirectory));
            layout.next(logincontainer);
        }

        btn_logout.setEnabled(true);
        //btn_donorRegisteration.setEnabled(false);
        //txtusername.setEnabled(false);
        //txtpassword.setEnabled(false);

    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_donorRegisterationRegisterationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_donorRegisterationRegisterationActionPerformed

        DonorRegistrationJPanel donorWorkAreaJPanel = new DonorRegistrationJPanel(logincontainer, system, donorDirectory, dB4OUtil);
        logincontainer.add("donorWorkAreaJPanel", donorWorkAreaJPanel);
        CardLayout layout=(CardLayout)logincontainer.getLayout();
        layout.next(logincontainer);
    }//GEN-LAST:event_btn_donorRegisterationRegisterationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_donorRegisteration;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblusername;
    private javax.swing.JPanel logincontainer;
    private javax.swing.JPanel loginjPanel;
    private javax.swing.JPanel logoutjPanel;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
