/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ProcurementTeamRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.OrganBankEnterprise;
import Business.Network.Network;
import Business.Organization.Facilities;
import Business.Organization.OrganOffice;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.Users.Users;
import Business.WorkQueue.OrganProcureWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noordeep
 */
public class ProcurementTeamJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcurementTeamJPanel
     */
     JPanel userProcessContainer;
    OrganizationDirectory organizationDirectory; 
    Enterprise enterprise;
    EcoSystem ecoSystem;
    Users account;
    Organization organization;
    Network network;
    
    public ProcurementTeamJPanel(JPanel userProcessContainer, Users account, Organization organization, Enterprise enterprise, EcoSystem business, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.ecoSystem=business;
        this.account = account;
        this.organization =organization;
        this.network=network;
        populate_tbl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_work_request = new javax.swing.JTable();
        btn_in_process = new javax.swing.JButton();
        btn_completed = new javax.swing.JButton();
        lbl_procurement_team_dashboard = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        tbl_work_request.setForeground(new java.awt.Color(153, 51, 0));
        tbl_work_request.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Patient", "Status", "Organs", "Patient", "Doctor"
            }
        ));
        tbl_work_request.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tbl_work_request.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(tbl_work_request);

        btn_in_process.setBackground(new java.awt.Color(255, 0, 51));
        btn_in_process.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_in_process.setForeground(new java.awt.Color(255, 255, 255));
        btn_in_process.setText("InProcess");
        btn_in_process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_in_processActionPerformed(evt);
            }
        });

        btn_completed.setBackground(new java.awt.Color(255, 0, 51));
        btn_completed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_completed.setForeground(new java.awt.Color(255, 255, 255));
        btn_completed.setText("Completed");
        btn_completed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_completedActionPerformed(evt);
            }
        });

        lbl_procurement_team_dashboard.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_procurement_team_dashboard.setForeground(new java.awt.Color(255, 0, 51));
        lbl_procurement_team_dashboard.setText("Procurement Team Dashboard");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/assistance.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(lbl_procurement_team_dashboard))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(303, 303, 303)
                                .addComponent(btn_in_process)
                                .addGap(54, 54, 54)
                                .addComponent(btn_completed)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_procurement_team_dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_in_process)
                    .addComponent(btn_completed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 543, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_in_processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_in_processActionPerformed

        int selectedRow = tbl_work_request.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select request to Process", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        OrganProcureWorkRequest orgwr = (OrganProcureWorkRequest)tbl_work_request.getValueAt(selectedRow, 0);
        boolean check;
        check=orgwr.getTeam().equalsIgnoreCase(organization.getOrgName());
                
        if(!check){
            JOptionPane.showMessageDialog(null, "This task is assigned to other team");
            return;
        }
        if(orgwr.getStatus().equals("Assigned")){
          orgwr.setStatus("InProcess");  
        }

     populate_tbl();
  
    }//GEN-LAST:event_btn_in_processActionPerformed

    private void btn_completedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_completedActionPerformed

       int selectedRow = tbl_work_request.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Select request to Complete", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        OrganProcureWorkRequest orgwr = (OrganProcureWorkRequest)tbl_work_request.getValueAt(selectedRow, 0);
        if(!orgwr.getStatus().equals("InProcess")){
        JOptionPane.showMessageDialog(null,"Request should be InProcess", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
                   if(organization instanceof Facilities){
                       orgwr.setStatus("Completed");
                   ((Facilities) organization).setCounterNumber(0);}

     populate_tbl();  
    }//GEN-LAST:event_btn_completedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_completed;
    private javax.swing.JButton btn_in_process;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_procurement_team_dashboard;
    private javax.swing.JTable tbl_work_request;
    // End of variables declaration//GEN-END:variables

    private void populate_tbl() {
         DefaultTableModel model = (DefaultTableModel) tbl_work_request.getModel();
         model.setRowCount(0);
         for(Network n: ecoSystem.getNetworkList()){
            if(n.getName().equalsIgnoreCase(network.getName())){
            for(Enterprise e: n.getEnterpriseList().getEnterpriseList()){
                if(e instanceof OrganBankEnterprise){
                    if(e.getWorkQueue()== null){
                        System.out.println("catched by repears");
                      break;}
                    for(WorkRequest wr: e.getWorkQueue().getWorkRequestList()){
                        if( wr.getStatus().equals("Assigned")|| wr.getStatus().equals("InProcess")|| wr.getStatus().equals("Completed")){
                            OrganProcureWorkRequest opr = (OrganProcureWorkRequest)wr;
                            System.out.println("In Ark space ship");
                            String a ="";
                            for( String s: opr.getOrganList()){
                                a= s+":"+a;
                            }
                            Object[] row = new Object[80];
                        row[0]= opr;
                        row[1] = opr.getMessage();
                        
                        row[1] = opr.getStatus();
                        row[2] = a;
                        
                        row[3] = opr.getPatient().getPatientName();
                        row[4] = opr.getPatient().getDoctor();
                        model.addRow(row);
                        }

                    }
                }
            }
            }
        }
    }
}
