/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Noordeep
 */
public class EnterpriseManagementJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EcoSystem system;
    ArrayList<String> entnet = new ArrayList<String>();

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    public EnterpriseManagementJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        loadEnterpriseTable();
        LoadComboBox();
        loadtable();
    }

    private void loadEnterpriseTable() {
        DefaultTableModel entTable = (DefaultTableModel) tbl_list_of_enterprises.getModel();
        entTable.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();
                entTable.addRow(row);
            }
        }
    }

    private boolean checkcurrentEnterprise(Enterprise.EnterpriseType type) {
        ArrayList<Enterprise.EnterpriseType> estEnterprises = new ArrayList<Enterprise.EnterpriseType>();
        for (Network network : system.getNetworkList()) {
            if (network == currentEnterprise_add_new_network.getSelectedItem()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    estEnterprises.add(enterprise.getEnterpriseType());
                }

            }
        }
        if (estEnterprises.contains(type)&&(type.getValue().equalsIgnoreCase("government")||type.getValue().equalsIgnoreCase("organ bank"))) {
            JOptionPane.showMessageDialog(null, "One enterprise allowed for the selected option");
            return true;
        }

        return false;
    }

    private void LoadComboBox() {
        currentEnterprise_add_new_network.removeAllItems();
        currentEnterprise_add_new_Type.removeAllItems();
        currentEnterprise_add_new_network.addItem("--Select--");
        currentEnterprise_add_new_Type.addItem("--Select--");
        currentEnterprises_dropdown.addItem("-All Enterprises-");
        for (Network network : system.getNetworkList()) {
            currentEnterprise_add_new_network.addItem(network);
            currentEnterprises_dropdown.addItem(network.toString());
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            currentEnterprise_add_new_Type.addItem(type);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_list_of_enterprises = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        currentEnterprise_add_new_network = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txt_Add_new_EntityName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        currentEnterprise_add_new_Type = new javax.swing.JComboBox();
        btn_addNewEnterprise = new javax.swing.JButton();
        btn_back_to_mainPage = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        currentEnterprises_dropdown = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        tbl_list_of_enterprises.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbl_list_of_enterprises.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tbl_list_of_enterprises.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_list_of_enterprises);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel1.setText("Network:");

        currentEnterprise_add_new_network.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        currentEnterprise_add_new_network.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentEnterprise_add_new_network.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentEnterprise_add_new_networkActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Enterprise Name:");

        txt_Add_new_EntityName.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Type of Enterprise:");

        currentEnterprise_add_new_Type.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        currentEnterprise_add_new_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentEnterprise_add_new_Type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentEnterprise_add_new_TypeActionPerformed(evt);
            }
        });

        btn_addNewEnterprise.setBackground(new java.awt.Color(0, 102, 153));
        btn_addNewEnterprise.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_addNewEnterprise.setForeground(new java.awt.Color(255, 255, 255));
        btn_addNewEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
        btn_addNewEnterprise.setText("Add");
        btn_addNewEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addNewEnterpriseActionPerformed(evt);
            }
        });

        btn_back_to_mainPage.setBackground(new java.awt.Color(0, 102, 153));
        btn_back_to_mainPage.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_back_to_mainPage.setForeground(new java.awt.Color(255, 255, 255));
        btn_back_to_mainPage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back3.png"))); // NOI18N
        btn_back_to_mainPage.setText("Back");
        btn_back_to_mainPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_back_to_mainPageActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("ENTERPRISES");

        jLabel7.setFont(new java.awt.Font("Cambria", 2, 18)); // NOI18N
        jLabel7.setText("Current enterprises");

        jLabel5.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Add Enterprise");

        currentEnterprises_dropdown.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        currentEnterprises_dropdown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentEnterprises_dropdownActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(currentEnterprises_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btn_back_to_mainPage)))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_Add_new_EntityName, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(currentEnterprise_add_new_Type, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentEnterprise_add_new_network, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_addNewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel4)
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(currentEnterprises_dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(currentEnterprise_add_new_network, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(currentEnterprise_add_new_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Add_new_EntityName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_addNewEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addComponent(btn_back_to_mainPage, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addNewEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addNewEnterpriseActionPerformed

        int counter = 0;
        String name = txt_Add_new_EntityName.getText();
        String city = currentEnterprise_add_new_network.getSelectedItem().toString();
        if (name.matches("^([A-Za-z]+)(\\s[A-Za-z]+)*\\s?$")) {
            name = name.trim();
            for (String s : entnet) {
                if (s.equalsIgnoreCase(name + city)) {
                    JOptionPane.showMessageDialog(null, "Please try aagain, The Enterprise already exists in this city");
                    counter++;
                    break;
                }
            }
            if (counter == 0) {
                entnet.add(name + city);
                Network network = (Network) currentEnterprise_add_new_network.getSelectedItem();
                Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) currentEnterprise_add_new_Type.getSelectedItem();

                if (network == null || type == null) {
                    JOptionPane.showMessageDialog(null, "Please try again, Invalid Input!");
                    return;
                }
                
                if (checkcurrentEnterprise(type)) {
                    return;

                } else {
                    Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
                    
                    loadEnterpriseTable();
                    txt_Add_new_EntityName.setText("");
                }
            }

        } else {
            JOptionPane.showMessageDialog(null, "Invalid input, Enterprise can only contain alphabets");
        }

    }//GEN-LAST:event_btn_addNewEnterpriseActionPerformed

    private void btn_back_to_mainPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_back_to_mainPageActionPerformed
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btn_back_to_mainPageActionPerformed


    private void currentEnterprise_add_new_TypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentEnterprise_add_new_TypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentEnterprise_add_new_TypeActionPerformed

    private void currentEnterprise_add_new_networkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentEnterprise_add_new_networkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentEnterprise_add_new_networkActionPerformed

    public void loadtable(){
        DefaultTableModel model = (DefaultTableModel) tbl_list_of_enterprises.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = enterprise.getEnterpriseType().getValue();
                    model.addRow(row);
                }
            
        }
    }
    
    private void currentEnterprises_dropdownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentEnterprises_dropdownActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbl_list_of_enterprises.getModel();
        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            if (network.getName() == currentEnterprises_dropdown.getSelectedItem()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    Object[] row = new Object[3];
                    row[0] = enterprise.getName();
                    row[1] = network.getName();
                    row[2] = enterprise.getEnterpriseType().getValue();
                    model.addRow(row);
                }
            }else if(currentEnterprises_dropdown.getSelectedIndex()==0){
                loadtable();
            }
        }
    }//GEN-LAST:event_currentEnterprises_dropdownActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addNewEnterprise;
    private javax.swing.JButton btn_back_to_mainPage;
    private javax.swing.JComboBox currentEnterprise_add_new_Type;
    private javax.swing.JComboBox currentEnterprise_add_new_network;
    private javax.swing.JComboBox<String> currentEnterprises_dropdown;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_list_of_enterprises;
    private javax.swing.JTextField txt_Add_new_EntityName;
    // End of variables declaration//GEN-END:variables
}
