/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthCare;
import Business.Organization.Organization;
import Business.Person.Patients;
import Business.Ranking;
import Business.Users.Users;
import Business.Waitlist.Wait;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Noordeep
 */
public class RequestOrganJpanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestOrganJpanel
     */
    JPanel userProcessContainer;
    Users userAccount;
    String id;
    Organization org;
    EcoSystem ecoSystem;
    Enterprise enterprise;
    Network network;
    Patients p;
    public RequestOrganJpanel(JPanel userProcessContainer, HealthCare organization, Users userAccount, Patients p, EcoSystem ecosystem, Enterprise enterprise, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.id=""+p.getPatientId();
        this.ecoSystem=ecosystem;
        this.p=p;
        this.org=organization;
        this.network=network;
        this.enterprise=enterprise;
        txt_patient_Id.setText(id);
        txt_patient_name.setText(this.p.getPatientName());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_patient_Id = new javax.swing.JTextField();
        txt_patient_name = new javax.swing.JTextField();
        request_organ_combo_box = new javax.swing.JComboBox<>();
        age_comboBox = new javax.swing.JComboBox<>();
        ped_status_comboBox = new javax.swing.JComboBox<>();
        survival_benefit_comboBox = new javax.swing.JComboBox<>();
        urgency_comboBox = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        jLabel1.setText("Organ Request");

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Patient ID :");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel3.setText("Patient Name :");

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel4.setText("Required Organ :");

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel5.setText("Age Group :");

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Pediatric Status :");

        jLabel7.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel7.setText("Survival Benefit :");

        jLabel8.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel8.setText("Urgency :");

        request_organ_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Heart", "Kidney", "Liver", "Lungs", "Pancreas", "Intestines" }));

        age_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "0-20", "20-35", "35-50", "50-65", ">65" }));

        ped_status_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Yes", "No" }));

        survival_benefit_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "85-100", "60-85", "50-60", "30-50", "<30" }));

        urgency_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Critical", "Not Critical" }));

        btn_submit.setBackground(new java.awt.Color(0, 102, 153));
        btn_submit.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btn_submit.setForeground(new java.awt.Color(255, 255, 255));
        btn_submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/submit.png"))); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_back.setBackground(new java.awt.Color(0, 102, 153));
        btn_back.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back3.png"))); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_patient_Id)
                                .addComponent(txt_patient_name)
                                .addComponent(request_organ_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(age_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ped_status_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(survival_benefit_comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(urgency_comboBox, 0, 256, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(88, 88, 88)
                                    .addComponent(btn_submit)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btn_back)))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_patient_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_patient_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(request_organ_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(age_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ped_status_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(survival_benefit_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(urgency_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btn_submit)
                .addGap(18, 18, 18)
                .addComponent(btn_back)
                .addGap(95, 95, 95))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {age_comboBox, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, ped_status_comboBox, request_organ_combo_box, survival_benefit_comboBox, txt_patient_Id, txt_patient_name, urgency_comboBox});

    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        boolean check;
        check=(ped_status_comboBox.getSelectedIndex()>0&&age_comboBox.getSelectedIndex()>0&&request_organ_combo_box.getSelectedIndex()>0&&survival_benefit_comboBox.getSelectedIndex()>0&&urgency_comboBox.getSelectedIndex()>0);
        if(check == false) {
            JOptionPane.showMessageDialog(null, "Please provide all parameters");
            return;
        }

        int dup=0;
        for(Wait w: ecoSystem.getWaitList()){
            if(w.getPatient().getPatientId()==p.getPatientId()&&w.getOrgan().equalsIgnoreCase(request_organ_combo_box.getSelectedItem().toString())){
               dup++; 
            }
        }
        
        check=(dup==0);
        if(!check){
            JOptionPane.showMessageDialog(null, "Patient is already in waitlist");
            return;
        }

        int score=0;
        if(ecoSystem.getWaitList().size()<1){
            score=calculateScore();
        }else{
            Collections.sort(ecoSystem.getWaitList());
            for(Wait w: ecoSystem.getWaitList()){
                if(w.getOrgan().equalsIgnoreCase(request_organ_combo_box.getSelectedItem().toString())){
                    score=w.getWaitlist()-1;
                    break;
                }else{
                    score=calculateScore();
                }
            }
        
        }
        
        Wait waitlist_val=new Wait(p,age_comboBox.getSelectedItem().toString(),ped_status_comboBox.getSelectedItem().toString(),survival_benefit_comboBox.getSelectedItem().toString(),urgency_comboBox.getSelectedItem().toString(),request_organ_combo_box.getSelectedItem().toString(),score,0);
        ecoSystem.addWaitlist(waitlist_val);

        DoctorWorkAreaJPanel doctorWorkArea=new DoctorWorkAreaJPanel(userProcessContainer, userAccount,(HealthCare) org,enterprise,ecoSystem,network);
        doctorWorkArea.load_wait_table();
        userProcessContainer.add("Lab test",doctorWorkArea);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        DoctorWorkAreaJPanel doctorWorkArea=new DoctorWorkAreaJPanel(userProcessContainer, userAccount,(HealthCare) org,enterprise,ecoSystem,network);
        doctorWorkArea.load_wait_table();
        userProcessContainer.add("Lab test",doctorWorkArea);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn_backActionPerformed
    public int calculateScore(){
        int counter=0;
        int age=age_comboBox.getSelectedIndex();
        int ped=ped_status_comboBox.getSelectedIndex();
        int sur=survival_benefit_comboBox.getSelectedIndex();
        int urg=urgency_comboBox.getSelectedIndex();
        if(age==1){
            counter=counter+10;
        }else if(age==2){
            counter=counter+8;
        }else if(age==3){
            counter=counter+6;
        }else if(age==4){
            counter=counter+4;
        }else if(age==5){
            counter=counter+2;
        }
        
        if(sur==1){
            counter=counter+10;
        }else if(sur==2){
            counter=counter+8;
        }else if(sur==3){
            counter=counter+6;
        }else if(sur==4){
            counter=counter+4;
        }else if(sur==5){
            counter=counter+2;
        }
        
        if(ped==1){
            counter=counter+10;
        }else if(ped==2){
            counter=counter+0;
        }
        
        if(urg==1){
            counter=counter+10;
        }else if(ped==2){
            counter=counter+5;
        }
        
        
        return counter;
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> age_comboBox;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox<String> ped_status_comboBox;
    private javax.swing.JComboBox<String> request_organ_combo_box;
    private javax.swing.JComboBox<String> survival_benefit_comboBox;
    private javax.swing.JTextField txt_patient_Id;
    private javax.swing.JTextField txt_patient_name;
    private javax.swing.JComboBox<String> urgency_comboBox;
    // End of variables declaration//GEN-END:variables
}
