/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.HealthCare;
import Business.Organization.Organization;
import Business.Person.Patients;
import Business.Users.Users;
import Business.WorkQueue.DiagnosticsWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Noordeep
 */
public class TestDataJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    Users userAccount;
    String id;
    Patients patient;
    String assist;
    Enterprise enterprise;
    HealthCare organization;
    EcoSystem ecosystem;
    Network network;
    /**
     * Creates new form TestDataJPanel
     */
    public TestDataJPanel(JPanel userProcessContainer, Users userAccount, String id,Patients patient,String assist,Enterprise enterprise,HealthCare organization, EcoSystem ecosystem,Network network) {
        initComponents();
        this.userAccount=userAccount;
        this.userProcessContainer=userProcessContainer;
        this.id=id;
        this.patient=patient;
        this.assist=assist;
        this.enterprise=enterprise;
        this.organization=organization;
        this.ecosystem=ecosystem;
        this.network=network;
        txt_test_report.setText(populatevalues());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_satisfied_with_report = new javax.swing.JButton();
        lbl_test_report = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_test_report = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 0, 51));

        txt_satisfied_with_report.setText("Okay");
        txt_satisfied_with_report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_satisfied_with_reportActionPerformed(evt);
            }
        });

        lbl_test_report.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        lbl_test_report.setText("Test Report");

        txt_test_report.setEditable(false);
        txt_test_report.setBackground(new java.awt.Color(0, 0, 0));
        txt_test_report.setColumns(20);
        txt_test_report.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        txt_test_report.setForeground(new java.awt.Color(255, 255, 255));
        txt_test_report.setRows(5);
        jScrollPane1.setViewportView(txt_test_report);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(txt_satisfied_with_report, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(lbl_test_report)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lbl_test_report)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_satisfied_with_report)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String populatevalues(){
        String test="            ******************** TEST RESULTS ***********************\n";
        test+="\nPatient ID : "+id+"\n";
        test+="\nPatient Name : "+patient.getPatientName()+"\n";
        test+="\nLab Assistant :"+assist+"\n";
        test+="**************************************************";
        
        
        for(int i=0;i<userAccount.getWorkQueue().getWorkRequestList().size();i++){
            if(userAccount.getWorkQueue().getWorkRequestList().get(i) instanceof DiagnosticsWorkRequest){
                if((""+((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getPatient().getPatientId()).equalsIgnoreCase(id)){
                    for(int j=0;j<((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getTests().size();j++){
                        test+="\n"+((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getTests().get(j) +" : "+((DiagnosticsWorkRequest) userAccount.getWorkQueue().getWorkRequestList().get(i)).getTestData().get(j)+"\n";
                    }
                }
            }
        
        }

    return test;
    }
   
    
    private void txt_satisfied_with_reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_satisfied_with_reportActionPerformed
        // TODO add your handling code here:
        DoctorWorkAreaJPanel satisfied_with_report=new DoctorWorkAreaJPanel(userProcessContainer,userAccount,organization,enterprise,ecosystem,network);
        userProcessContainer.add("Customer Adding",satisfied_with_report);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_txt_satisfied_with_reportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_test_report;
    private javax.swing.JButton txt_satisfied_with_report;
    private javax.swing.JTextArea txt_test_report;
    // End of variables declaration//GEN-END:variables
}
