

package userinterface.CreateAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author  Noordeep
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem ecoSystem;
    Network network;
    /** Creates new form AdminWorkAreaJPanel */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem ecoSystem,Network network) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.ecoSystem=ecoSystem;
        this.network=network;
        System.out.println(enterprise.getOrgName().concat("hospital"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_Admin_Dashboard = new javax.swing.JLabel();
        btn_manage_users = new javax.swing.JButton();
        btn_manage_organization = new javax.swing.JButton();
        btn_manage_employees = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        txt_Admin_Dashboard.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        txt_Admin_Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txt_Admin_Dashboard.setText("ADMIN DASHBOARD");

        btn_manage_users.setBackground(new java.awt.Color(0, 102, 153));
        btn_manage_users.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_manage_users.setForeground(new java.awt.Color(255, 255, 255));
        btn_manage_users.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminDashboardManageUserAccount1.png"))); // NOI18N
        btn_manage_users.setText("   Manage User Accounts");
        btn_manage_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manage_usersActionPerformed(evt);
            }
        });

        btn_manage_organization.setBackground(new java.awt.Color(0, 102, 153));
        btn_manage_organization.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_manage_organization.setForeground(new java.awt.Color(255, 255, 255));
        btn_manage_organization.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminDashboardManageOraganisation.png"))); // NOI18N
        btn_manage_organization.setText("  Manage Organization");
        btn_manage_organization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manage_organizationActionPerformed(evt);
            }
        });

        btn_manage_employees.setBackground(new java.awt.Color(0, 102, 153));
        btn_manage_employees.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        btn_manage_employees.setForeground(new java.awt.Color(255, 255, 255));
        btn_manage_employees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AdminDashboardManageEmployees.png"))); // NOI18N
        btn_manage_employees.setText("Manage Employees");
        btn_manage_employees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manage_employeesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txt_Admin_Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(260, 260, 260)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_manage_organization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_manage_employees, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(262, 262, 262)
                            .addComponent(btn_manage_users, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(661, 661, 661))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(txt_Admin_Dashboard)
                .addGap(52, 52, 52)
                .addComponent(btn_manage_organization)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_manage_employees)
                .addGap(12, 12, 12)
                .addComponent(btn_manage_users)
                .addContainerGap(565, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_manage_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manage_usersActionPerformed
        UserManagement manageusers = new UserManagement(userProcessContainer, enterprise);
        userProcessContainer.add("ManageUserAccountJPanel", manageusers);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn_manage_usersActionPerformed

    private void btn_manage_organizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manage_organizationActionPerformed
        OrganizationManagementJPanel manageorganization = new OrganizationManagementJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise);
        userProcessContainer.add("manageOrganizationJPanel", manageorganization);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn_manage_organizationActionPerformed

    private void btn_manage_employeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manage_employeesActionPerformed

        EmployeeManagement manageemployees = new EmployeeManagement(userProcessContainer, enterprise.getOrganizationDirectory(),enterprise,ecoSystem);
        userProcessContainer.add("manageOrganizationJPanel", manageemployees);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btn_manage_employeesActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_manage_employees;
    private javax.swing.JButton btn_manage_organization;
    private javax.swing.JButton btn_manage_users;
    private javax.swing.JLabel txt_Admin_Dashboard;
    // End of variables declaration//GEN-END:variables
    
}
